stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data/heart.csv
    outs:
    - data/raw/heart.csv
  
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/heart.csv
    outs:
    - data/processed/train_heart.csv
    - data/processed/test_heart.csv
  
  train_and_evaluate:
    cmd: python src/train_and_eval.py --config=params.yaml
    deps:
    - data/processed/train_heart.csv
    - data/processed/test_heart.csv 
    - src/train_and_eval.py
    params:
    - estimators.RandomForestClassifier.params.n_estimators
    - estimators.RandomForestClassifier.params.criterion

  log_production_model:
    cmd: python src/log_production_model.py --config=params.yaml
    deps:
    - src/log_production_model.py
