base:
  project: heart_disease-project
  random_state: 42
  target_col: target

data_source:
  s3_source: data/heart.csv

load_data:
  raw_dataset: data/raw/heart.csv

split_data:
  train_path: data/processed/train_heart.csv
  test_path: data/processed/test_heart.csv
  test_size: 0.2

estimators:
  RandomForestClassifier:
    params:
      n_estimators: 10
      criterion: 'gini'
      #n_estimators: 300
      #criterion: 'entropy'

model_dir: saved_models
webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: RandomForestClassifier
  run_name: mlops
  registered_model_name: RandomForestClassifier_nmodel
  remote_server_uri: http://0.0.0.0:1234
